In [1]:
import numpy

In [2]:
def one_row(n, low, high):
    """Return one row of numbers
    
    Args:
        n (int): length
        low (int): lowest possible number
        high (int): highest possible number
    Returns:
        1D numpy array
    """
    return numpy.random.randint(low, high=high, size=n)

In [3]:
def half_mirror(m, n, low, high):
    """Return a matrix
    
    Args:
        m (int): number of rows
        n (int): number of columns
        low (int): lowest possible number
        high (int): highest possible number
    Returns:
        2D numpy array
    """
    return numpy.vstack([one_row(n, low, high) for i in range(m)])
    

In [12]:
def flatten(a):
    """Flatten a 2D array"""
    size = numpy.prod(numpy.shape(a))
    return numpy.reshape(a, (size,))

In [14]:
def full_mirror(m, n, low, high):
    """Return a matrix
    Returns a symmetric image with 50% probability
    
    Args:
        m (int): half mirror size (excluding the middle row)
        n (int): number of columns
        low (int): lowest possible number
        high (int): highest possible number
    Returns:
        2D numpy array
    """
    coin = numpy.random.random()
    if coin > 0.5:
        return  numpy.vstack([
                    half_mirror(m, n, low, high),
                    numpy.zeros(n),
                    half_mirror(m, n, low, high)
                ]).reshape(())
    else:
        half = half_mirror(m, n, low, high)
        return numpy.vstack([
                half,
                numpy.zeros(n),
                half[::-1, :]
            ])

In [38]:
def label_full_mirror(a):
    m, n = numpy.shape(a)
    top = a[0:(m-1)//2, :]
    bottom = a[(m+1)//2:, :]
    print(top)
    return numpy.amax(
            numpy.absolute(top - bottom[-1::-1])
        ) < 1.0e-5

In [26]:
a = full_mirror(5, 5, 0, 9)
a

array([[ 5.,  0.,  2.,  3.,  1.],
       [ 7.,  5.,  3.,  7.,  7.],
       [ 7.,  0.,  5.,  5.,  1.],
       [ 4.,  8.,  7.,  6.,  3.],
       [ 5.,  8.,  4.,  4.,  6.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 5.,  8.,  4.,  4.,  6.],
       [ 4.,  8.,  7.,  6.,  3.],
       [ 7.,  0.,  5.,  5.,  1.],
       [ 7.,  5.,  3.,  7.,  7.],
       [ 5.,  0.,  2.,  3.,  1.]])

In [24]:
a.shape

(11, 5)

In [37]:
label_full_mirror(a)

False

In [29]:
a[0, :]

array([ 5.,  0.,  2.,  3.,  1.])

In [33]:
a[0, :][-1:1:-1]

array([ 1.,  3.,  2.])